data_cheat_site/cheat_py/urls.py
from django.urls import path

from . import views

app_name = "cheat_py"

urlpatterns = [
    path("", views.index, name="index"),
]

data_cheat_site/cheat_sql/urls.py
from django.urls import path

from . import views

app_name = "cheat_sql"
urlpatterns = [
    path("", views.index, name="index"),
    path("<slug:slug>/", views.chapter_ui, name="chapter_ui"),
    path("<slug:slug>/<slug:slug2>/", views.lesson_ui, name="lesson_ui"),
]

data_cheat_site/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.ContributorsView.as_view(), name="about"),
]

data_cheat_site/data_cheat_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('sql/', include('cheat_sql.urls')),
    path('python/', include('cheat_py.urls')),
]

data_cheat_site/cheat_py/models.py
from django.db import models

# Create your models here.

data_cheat_site/cheat_sql/models.py
from django.db import models
from django.utils.text import slugify
import random

# Create your models here.


class Chapter(models.Model):
    chapter_name = models.CharField(max_length=200, unique=True)
    chapter_number = models.IntegerField(default=10000)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    COURSES = [
        ("sql", "SQL"),
        ("python", "Python"),
        ]
    course = models.CharField(
        max_length=20,
        choices=COURSES,
        default="sql",
    )
    # chapter_number = models.IntegerField(primary_key=True)
    chapter_description = models.TextField()
    published = models.BooleanField(default=False)
    chapter_date = models.DateTimeField("date published")

    def __str__(self):
        return self.chapter_name
    
    def nb_ch(self):
        return Chapter.objects.count()
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.chapter_name)
        #Check if the chapter_number already exists for another object
        if Chapter.objects.filter(chapter_number=self.chapter_number).exists():
            # Increment chapter_number of all chapters with chapter_number greater than or equal to the current chapter's chapter_number
            Chapter.objects.filter(chapter_number__gte=self.chapter_number).exclude(id=self.id).update(chapter_number=models.F('chapter_number') + 1)
        super().save(*args, **kwargs)


class Clause(models.Model):
    # lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    clause_name = models.CharField(max_length=200)
    VARIANTS = [
        ("gernaral_sql", "General SQL"),
        ("pl_sql", "PL/SQL"),
        ("transact_sql", "Transact-SQL"),
        ("mysql", "MySQL"),
        ("postgresql", "PostgreSQL"),
        ("mssql", "MS SQL Server"),
        ("oracle", "Oracle"),
    ]
    DBS = [
        ("mysql", "MySQL"),
        ("postgresql", "PostgreSQL"),
        ("mssql", "MS SQL Server"),
        ("oracle", "Oracle"),
        ("all", "All"),
    ]
    db = models.CharField(
        max_length=20,
        choices=DBS,
        default="all",
    )
    variant = models.CharField(
        max_length=20,
        choices=VARIANTS,
        default="gernaral_sql",
    )
    clause_description = models.TextField()

class Image(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='lessons_image/')


class Lesson(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    lesson_name = models.CharField(max_length=200)
    lesson_number = models.IntegerField(default=10000)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    LESSON_TYPES = [
        ("lab", "Lab"),
        ("lecture", "Lecture"),
        ("quiz", "Quiz"),
    ]
    lesson_type = models.CharField(
        max_length=20,
        choices=LESSON_TYPES,
        default="lecture",
    )
    lesson_clauses = models.ManyToManyField(Clause,blank=True)
    LEVELS = [
        ("beginner", "Beginner"),
        ("intermediate", "Intermediate"),
        ("advanced", "Advanced"),
    ]
    level = models.CharField(
        max_length=20,
        choices=LEVELS,
        default="beginner",
    )
    lesson_description = models.TextField()
    text_content  = models.FileField(upload_to='lessons_text/', blank=True)
    images = models.ManyToManyField(Image)
    published = models.BooleanField(default=False)
    lesson_date = models.DateTimeField("date published")

    def __str__(self):
        return self.lesson_name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.lesson_name)
        #Check if the lesson_number already exists for another object
        if Lesson.objects.filter(lesson_number=self.lesson_number).exists():
            # Increment lesson_number of all chapters with lesson_number greater than or equal to the current chapter's lesson_number
            Lesson.objects.filter(lesson_number__gte=self.lesson_number).exclude(id=self.id).update(lesson_number=models.F('lesson_number') + 1)
        super().save(*args, **kwargs)

data_cheat_site/core/models.py
from django.db import models

# Create your models here.
from django.conf import settings


class Course(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    app_names = [app.split(".")[0] for app in settings.INSTALLED_APPS if not app.startswith("django")]
    APPS_LIST = list(zip(app_names, app_names))
    app_name = models.CharField(max_length=50, choices=APPS_LIST,default=app_names[0])
    #syllabus = models.TextField()
    #logo = models.ImageField()
    def __str__(self):
        return self.name
    
class Contributor(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    description = models.TextField()
    #bio = models.TextField()
    #avatar = models.ImageField()
    email = models.EmailField()
    def __str__(self):
        return self.name

data_cheat_site/cheat_py/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the Python index. It's not yet available")

data_cheat_site/cheat_sql/views.py
from django.shortcuts import render
from django.conf import settings

from .models import Chapter, Lesson, Clause, Image
import markdown, os
# Create your views here.

# test view
from django.http import HttpResponse


def index(request):

    # Query all chapters
    chapters = Chapter.objects.all().order_by("chapter_number")

    # Create a list of tuples, each containing a chapter and its related lessons
    chapter_lessons = [(chapter, Lesson.objects.filter(chapter=chapter).order_by("lesson_number")) for chapter in chapters]

    # Pass the list to the context
    context = {
        "chapter_lessons": chapter_lessons,
    }
    return render(request, "cheat_sql/base.html", context)

def chapter_ui(request, slug):
    
    # Query the chapter with the slug
    chapter = Chapter.objects.get(slug=slug)

    # Query all lessons related to the chapter
    lessons = Lesson.objects.filter(chapter=chapter).order_by("lesson_number")

    # Create a list of tuples, each containing a lesson and its related clauses
    #lesson_clauses = [(lesson, Clause.objects.filter(lesson=lesson)) for lesson in lessons]

    # Pass the list to the context
    context = {
        "chapter": chapter,
        "lessons": lessons,
    }
    return render(request, "cheat_sql/chapter.html", context)


def lesson_ui(request, slug, slug2):

    chapter = Chapter.objects.get(slug=slug)
    lesson = Lesson.objects.filter(chapter=chapter).get(slug=slug2)

    file_path = os.path.join(settings.MEDIA_ROOT, lesson.text_content.name)

    # Read the file content
    with open(file_path, 'r') as file:
        md_content = markdown.markdown(file.read())

    context = {
        "lesson": lesson,
        "md_content": md_content
    }
    return render(request, "cheat_sql/lesson_ui.html", context)
    

data_cheat_site/core/views.py
from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Course, Contributor
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic

#from django.urls import reverse

# Create your views here.

class IndexView(generic.ListView):
    template_name = "core/index.html"
    context_object_name = "course_list"

    def get_queryset(self):
        return Course.objects.all()

class ContributorsView(generic.ListView):
    template_name = "core/about.html"
    context_object_name = "contributors"
    
    def get_queryset(self):
        return Contributor.objects.all()

data_cheat_site/cheat_sql/templates/cheat_sql/base.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container_fluid p-5 bg-light">
    {% for ch, lessons in chapter_lessons %}
      <div class="card">
        <h2 class="text-start"><a href="/sql/{{ch.slug}}">Chapter {{ch.chapter_number}}: {{ ch.chapter_name }}</a></h2>
        <p class="text-start">{{ ch.chapter_description }}</p>
        {% for lesson in lessons %}
        <div class="card">
          <h3 class="text-start"><a href=""> Lesson {{lesson.lesson_number}}: {{ lesson.lesson_name }}</a></h3>
          <p class="text-start">{{ lesson.lesson_description }}</p>
        </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

data_cheat_site/cheat_sql/templates/cheat_sql/chapter.html
{% extends 'cheat_sql/base.html' %}

{% block content %}
  <div class="container_fluid p-5 bg-light">
    <div class="card">
      <h2 class="text-start">Chapter {{ Chapter.chapter_number }}: {{ chapter.chapter_name }}</h2>
      <p class="text-start">{{ chapter.chapter_description }}</p>
    </div>
    <div class="container_fluid p-5 bg-light">
      {% for lesson in lessons %}
        <div class="card">
          <h2 class="text-start"><a href="/sql/{{chapter.slug}}/{{lesson.slug}}">Lesson {{ lesson.lesson_number }}: {{ lesson.lesson_name }}</a></h2>
          <p class="text-start">{{ lesson.lesson_description }}</p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

data_cheat_site/cheat_sql/templates/cheat_sql/lesson_ui.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container_fluid p-5 bg-light">
    <div class="card">
      <h2 class="text-start">Lesson {{ lesson.lesson_number }}: {{ lesson.lesson_name }}</h2>
      <p class="text-start">{{ lesson.lesson_description }}</p>
    </div>
    <div class="card">
      <p class="text-start">{{ md_content| safe}}</p>
    </div>
  </div>
{% endblock %}

data_cheat_site/core/templates/core/about.html
{% extends "core/base.html" %} 
{% block title %} DCS5.0 |About {% endblock %}

{% block content %}
<div class="container_fluid p-5 bg-light">
  <h2>Project Creator</h2>
  <div class="card m-2 p-2">
    <p>Serginau LOUIS</p>
    <p>BI Analyst at Digicel</p>
    <p>Project creator and Main contributor</p>
  </div>
  </div>

  <div class="container_fluid p-5 bg-light">
    <h2>Contributors</h2>
  {% if contributors %}
  {% for contributor in contributors %}
  <div class="card m-2 p-2">
    <p>{{ contributor.name }}</p>
    <p>{{ contributor.position }}</p>
    <p>{{ contributor.description }}</p>
  </div>
  {% endfor %} {% else %}
  <p>No others Contributors.</p>
  {% endif %}
</div>
{% endblock %}

data_cheat_site/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Data Cheat Site
      {% endblock %}
    </title>
  </head>
  <body>
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_messages %}

    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'core:index' %}">Data Cheat Site</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:about' %}">About</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Courses</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <!--  DYNAMIC MENU
                  {% for course in course_list %}
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url course.app_name|add:':index' %}"
                      >{{course.name}}</a
                    >
                  </li>
                  {% endfor %}
                   -->
                  <li>
                    <a class="dropdown-item" href="{% url 'cheat_sql:index' %}">SQL</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'cheat_py:index' %}">Python</a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}

      {% endblock %}
    </main>

    {% include 'core/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

data_cheat_site/core/templates/core/footer.html
<footer>
  <div class="footer bg-dark text-white text-center p-3 fixed-bottom">
    <p>&copy; copyright 2025 - Serginau LOUIS</p>
    <p>
      Visit <a href="https://github.com/slouis5" target="_blank">my Github Profile</a> <br />
      or my <a href="https://linkedin.com/in/slouis5" target="_blank">LinkedIn Profile</a> for more
      information.
    </p>
  </div>
</footer>

data_cheat_site/core/templates/core/index.html
{% extends "core/base.html" %} {% block content %} {% if course_list %}
<div class="container_fluid p-5 bg-light">
  <h2>Courses</h2>

  {% for course in course_list %}
  <div class="card m-2 p-2">
    <h2><a href="{% url course.app_name|add:':index' %}" > {{ course.name }}<a></h2>
    <p class="fst-italic">{{ course.description }}</p>
  </div>
  {% endfor %} {% else %}
  <p>No Courses are available.</p>
  {% endif %}
</div>
{% endblock %}